"""Optional full-value and encoder interoperability checks against Garmin's SDK.

With no paths, uses self-contained messages generated by Garmin's encoder.
With --samples, also checks every supplied FIT file. Install garmin-fit-sdk==21.217.0
only in the verification environment; it is not a fittie dependency.
"""

from __future__ import annotations

import argparse
import math
from collections.abc import Mapping
from io import BytesIO
from pathlib import Path

from garmin_fit_sdk import Decoder, Stream
from garmin_fit_sdk import Encoder as GarminEncoder

from fittie import DecodeOptions, decode, encode


def equal(actual, expected):
    if isinstance(actual, Mapping) and isinstance(expected, Mapping):
        return actual.keys() == expected.keys() and all(
            equal(v, expected[k]) for k, v in actual.items()
        )
    if isinstance(actual, (list, tuple)) and isinstance(expected, (list, tuple)):
        return len(actual) == len(expected) and all(
            equal(a, b) for a, b in zip(actual, expected)
        )
    if isinstance(actual, (int, float)) and isinstance(expected, (int, float)):
        return (math.isnan(actual) and math.isnan(expected)) or math.isclose(
            actual, expected, rel_tol=1e-10, abs_tol=1e-7
        )
    return actual == expected


def synthetic():
    encoder = GarminEncoder()
    for message in [
        {"mesg_num": 0, "type": 4, "manufacturer": 1, "time_created": 1_000_000_000},
        {
            "mesg_num": 20,
            "timestamp": 1_000_000_000,
            "speed": 3.141,
            "altitude": 120.2,
            "heart_rate": 120,
        },
        {
            "mesg_num": 20,
            "timestamp": 1_000_000_001,
            "speed": 3.2,
            "altitude": 121.4,
            "heart_rate": 130,
        },
        {"mesg_num": 21, "event": 11, "data": 3200},
        {"mesg_num": 27, "duration_type": 11, "target_type": 1, "target_value": 80},
        {"mesg_num": 13, "target_distance": 1234.56, "precise_target_speed": 3.123456},
        {
            "mesg_num": 412,
            "start_time": 1_000_000_000,
            "end_time": 1_000_000_100,
            "is_deleted": 0,
        },
        {"mesg_num": 470, "timestamp": 1_000_000_000, "severity": 1},
    ]:
        encoder.write_mesg(message)
    return bytes(encoder.close())


def verify(payload, name):
    options = DecodeOptions(
        convert_types_to_strings=True,
        convert_datetimes_to_dates=True,
        merge_heart_rates=True,
    )
    files = decode(BytesIO(payload), options=options)
    compared = 0
    offset = 0
    for file in files:
        # Encode each member separately; Garmin's Python SDK expects one member.
        encoded = encode(file)
        member_size = file.header.length + file.header.data_size + 2
        reference, errors = Decoder(
            Stream.from_byte_array(payload[offset : offset + member_size])
        ).read()
        offset += member_size
        if errors:
            raise AssertionError(f"{name}: Garmin rejected original data: {errors}")
        _, errors = Decoder(Stream.from_byte_array(encoded)).read()
        if errors:
            raise AssertionError(f"{name}: Garmin rejected encoded data: {errors}")
        descriptions = {
            d["key"]: (d["developer_data_index"], d["field_definition_number"])
            for d in reference.get("field_description_mesgs", ())
        }
        for group, messages in file.data_messages.items():
            sdk_messages = reference.get(group + "_mesgs", ())
            if len(messages) != len(sdk_messages):
                raise AssertionError(f"{name}.{group}: message count mismatch")
            for index, (message, expected) in enumerate(zip(messages, sdk_messages)):
                for key, value in expected.items():
                    if key == "key":
                        continue
                    if key == "developer_fields":
                        actual = message.developer_fields or {}
                        expected_dev = {descriptions[k]: v for k, v in value.items()}
                        match = equal(actual, expected_dev)
                    else:
                        match = key in message.fields and equal(
                            message.fields[key], value
                        )
                    if not match:
                        raise AssertionError(
                            f"{name}.{group}[{index}].{key}: {message.fields.get(key)!r} != {value!r}"
                        )
                    compared += 1
        again = decode(BytesIO(encoded), options=options)[0]
        if not equal(
            [m.fields for m in file.messages], [m.fields for m in again.messages]
        ):
            raise AssertionError(f"{name}: fittie round-trip changed fields")
    return compared


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--samples", type=Path, nargs="*", default=[])
    args = parser.parse_args()
    corpus = [("Garmin-generated", synthetic())]
    for path in args.samples:
        paths = sorted(path.glob("*.fit")) if path.is_dir() else [path]
        corpus.extend((p.name, p.read_bytes()) for p in paths)
    count = sum(verify(data, name) for name, data in corpus)
    print(
        f"{len(corpus)} files: {count} compared values; Garmin accepted every encoded member; zero unexpected differences."
    )


if __name__ == "__main__":
    main()
