name: Generate documentation
on:
  push:
    tags:
      - v*
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.6.9"
          python-version: 3.12
      - run: uv python install
      - run: uv sync --group docs
      - run: mkdocs gh-deploy --force
