name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.9"

    - name: Build package
      run: uv sync && uv build

    - name: Publish package
      run: uv publish --token "${{ secrets.PYPI_API_TOKEN }}"
